# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Surcursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Surcursal')),
                ('calle', models.CharField(max_length=150, verbose_name='Nombre de la Calle')),
                ('colonia', models.CharField(max_length=150, verbose_name='Nombre de la Colonia')),
                ('numeroExterior', models.IntegerField(blank=True, null=True, verbose_name='Numero Exterior')),
                ('numeroInterior', models.IntegerField(blank=True, null=True, verbose_name='Numero Interior')),
                ('codigoPostal', models.IntegerField(blank=True, null=True, verbose_name='Codigo Postal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Surcursal', verbose_name='Sucursal'),
        ),
    ]
